In [26]:
import ast

#La funzione restituisce l'output-value per il test x sulla base dei k elementi del TS più vicini ad x
def knn(testSet, x, k):
    tmpTS = testSet
    nH = []
    neighbor = []
    while(len(nH)<k):
        neighbor = nearest(x, tmpTS)
        nH.append(neighbor)
        tmpTS.remove(neighbor) # rimuoviamo il vicino appena trovato dal TS temporaneo
    return str(avg(nH))

# La funzione nearest() trova l'elemento più vicino ad x nel TS
def nearest(x, testSet):
    nearest = []
    minDist = 10000
    for el in testSet:
        dist = 0
        for i in range(1, len(el)):
            # la distanza di due elementi è data dalla somma dei valori assoluti delle differenze dei singoli campi
            dist += abs(ast.literal_eval(x[i]) - ast.literal_eval(el[i]))
        if(dist<minDist):
            nearest = el
            minDist = dist
    return nearest

# La funzione avg() calcola la media degli output-value del vicinato
def avg(nH):
    sum = 0
    for el in nH:
        sum += int(el[0])
    return int(sum/len(nH))

In [27]:
# il TS è letto dal file, in cui i campi degli elementi sono tutti Interi e Reali
ts = []
with open("wine.data") as file:
    for line in file:
        line = line.replace("\n", '')
        line = line.split(",")
        ts.append(line)

# x è il nuovo elemento da inserire nel TS, il quale non ha un output-value assegnato
# k è la grandezza del vicinato sulla base del quale l'algoritmo assegna l'output-value
x = ['', '13.86', '1.51', '2.67', '25', '86', '2.95', '2.86', '.21', '1.87', '3.38', '1.36', '3.16', '410']
k = int(input("inserisci k: "))

print("\n# Test x:", x, "\n# Neighbourhood's size k:", k )
x[0] = knn(ts, x, k)

print("\n# L'output-value assegnato a x è: ", x[0])
print("# Test x:", x)

inserisci k: 1

# Test x: ['', '13.86', '1.51', '2.67', '25', '86', '2.95', '2.86', '.21', '1.87', '3.38', '1.36', '3.16', '410']
# Neighbourhood's size k: 1

# L'output-value assegnato a x è:  2
# Test x: ['2', '13.86', '1.51', '2.67', '25', '86', '2.95', '2.86', '.21', '1.87', '3.38', '1.36', '3.16', '410']

In [28]:
# mapping dei valori non numerici in interi, mantenendone la semantica
def mapping(df):
    for (column, data) in df.iteritems():
        for i in range(len(df[column])):
            if(df[column][i]=="vhigh" or df[column][i]=="vgood"):
                df[column][i]='3'
            if(df[column][i]=="high" or df[column][i]=="big" or df[column][i]=="good"):
                df[column][i]='2'
            if(df[column][i]=="med" or df[column][i]=="acc"):
                df[column][i]='1'
            if(df[column][i]=="low" or df[column][i]=="small" or df[column][i]=="unacc"):
                df[column][i]='0'
            if(df[column][i]=="5more" or df[column][i]=="more"):
                df[column][i]='5'
    return df

# formattatore di dataset in una matrice
def formatter(df):
    ts = []
    j = 0
    for index, row in df.iterrows():
        el = []
        for i in row:
            el.append(i)
        ts.append(el)
    return ts

In [29]:
import pandas as pd    

df = pd.read_csv("car.data")

# ridefinizione ordinamento colonne, dove classValues è loutput del TS
columns_titles = ["classValues", "maint","doors", "persons", "lug_boot", "safety", "buying"]
df=df.reindex(columns=columns_titles)

df

     classValues  maint  doors persons lug_boot safety buying
0          unacc  vhigh      2       2    small    low  vhigh
1          unacc  vhigh      2       2    small    med  vhigh
2          unacc  vhigh      2       2    small   high  vhigh
3          unacc  vhigh      2       2      med    low  vhigh
4          unacc  vhigh      2       2      med    med  vhigh
...          ...    ...    ...     ...      ...    ...    ...
1723        good    low  5more    more      med    med    low
1724       vgood    low  5more    more      med   high    low
1725       unacc    low  5more    more      big    low    low
1726        good    low  5more    more      big    med    low
1727       vgood    low  5more    more      big   high    low

[1728 rows x 7 columns]

In [31]:
# x è il nuovo elemento da inserire nel TS, il quale non ha un output-value assegnato
# k è la grandezza del vicinato sulla base del quale l'algoritmo assegna l'output-value
x = pd.DataFrame({"classValues": [""], 
                  "maint": ["low"], 
                  "doors": ['3'], 
                  "persons": ['4'], 
                  "lug_boot": ["med"], 
                  "safety": ["med"], 
                  "buying": ["low"]
                 })
x=mapping(x)
df=mapping(df)

k = int(input("inserisci k: "))

print("\n# Test x:\n\n", x, "\n\n# Neighbourhood's size k:", k )

ts = formatter(df)
x = formatter(x)
print(x)



x[0][0] = knn(ts, x[0], k)

print("\n# L'output-value assegnato a x è: ", x[0])
print("# Test x:", x[0])

inserisci k: 1

# Test x:

   classValues maint doors persons lug_boot safety buying
0                 0     3       4        1      1      0

# Neighbourhood's size k: 1
[['', '0', '3', '4', '1', '1', '0']]

# L'output-value assegnato a x è:  ['1', '0', '3', '4', '1', '1', '0']
# Test x: ['1', '0', '3', '4', '1', '1', '0']